Repository odpf/optimus, pull requests merged in 2021-09, with the labels that each got.

#55 refactor: properly inject logger from the top in the required packages
  api/handler/v1/adapter.go
  api/handler/v1/adapter_test.go
  api/handler/v1/runtime.go
  api/handler/v1/runtime_test.go
  cmd/admin.go
  cmd/admin_build_instance.go
  cmd/admin_get_status.go
  cmd/commands.go
  cmd/config.go
  cmd/create.go
  cmd/deploy.go
  cmd/logger.go
  cmd/render.go
  cmd/replay.go
  cmd/serve.go
  cmd/server/server.go
  cmd/validate.go
  cmd/version.go
  config/loader.go
  core/logger/logger.go
  datastore/service.go
  datastore/service_test.go
  ext/datastore/bigquery/bigquery.go
  ext/datastore/bigquery/dataset.go
  ext/datastore/bigquery/dataset_spec.go
  ext/datastore/bigquery/dataset_spec_test.go
  ext/datastore/bigquery/external_table.go
  ext/datastore/bigquery/factory.go
  ext/datastore/bigquery/standard_view.go
  ext/datastore/bigquery/table.go
  ext/datastore/bigquery/table_spec.go
  ext/notify/slack/slack.go
  ext/notify/slack/slack_test.go
  go.mod
  go.sum
  instance/go_engine.go
  instance/jinja_engine.go
  instance/jinja_engine_test.go
  instance/service.go
  instance/service_test.go
  job/compiler.go
  job/event.go
  job/event_test.go
  job/replay.go
  job/replay_manager.go
  job/replay_manager_test.go
  job/replay_syncer.go
  job/replay_syncer_test.go
  job/replay_worker.go
  job/replay_worker_test.go
  job/service.go
  main.go
  plugin/base/client.go
  plugin/gen.go
Labels: refactor

#78 refactor: rename dryrun replay methods
  .github/workflows/lint.yml
  .gitignore
  .golangci.yml
  Makefile
  api/handler/v1/runtime.go
  api/handler/v1/runtime_test.go
  api/proto/odpf/optimus/runtime_service.pb.go
  api/proto/odpf/optimus/runtime_service.pb.gw.go
  api/proto/odpf/optimus/runtime_service_grpc.pb.go
  api/third_party/openapi/odpf/optimus/runtime_service.swagger.json
  cmd/replay.go
  ext/scheduler/prime/planner.go
Labels: refactor

#81 docs: configuration required for airflow2
  .optimus.sample.yaml
  Makefile
  api/proto/odpf/optimus/scheduler/cluster.pb.go
  ext/scheduler/airflow2/README.md
  ext/scheduler/airflow2/airflow.go
  main.go
Labels: documentation

#86 fix: deploy grpc stream should be concurrent safe
  .github/workflows/build.yml
  .github/workflows/integration-test.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .optimus.sample.yaml
  Makefile
  api/handler/v1/runtime.go
  cmd/deploy.go
  cmd/server/server.go
  cmd/version.go
  docs/docs/concepts/overview.md
  go.mod
  go.sum
  job/dependency_resolver.go
  job/dependency_resolver_test.go
  job/priority_resolver.go
  job/priority_resolver_test.go
  job/replay.go
  job/replay_test.go
  job/service.go
  job/service_test.go
  main.go
  meta/service.go
  meta/service_test.go
  mock/job.go
  models/job.go
  plugin/base/client.go
  plugin/base/connector.go
  plugin/cli/client.go
  plugin/dependencyresolver/client.go
  run/service.go
  run/service_test.go
  store/postgres/job_spec_adapter.go
  store/postgres/jobrun_repository.go
  store/store.go
Labels: bug
