Repository odpf/optimus, pull requests merged in 2022-09, with the labels that each got.

#614 fix: fix sensor to pass version information to compute the start & end times
  api/handler/v1beta1/job_run.go
  api/handler/v1beta1/job_run_test.go
  client/cmd/internal/survey/job_create.go
  ext/scheduler/airflow2/resources/__lib.py
  ext/scheduler/airflow2/resources/base_dag.py
  ext/scheduler/airflow2/resources/expected_compiled_template.py
  models/window.go
  models/window_v1.go
  models/window_v1_test.go
  models/window_v2.go
  models/window_v2_test.go
Labels: bug

#621 fix : handle deletions for both namespace id vs namespace name folders
  ext/scheduler/airflow2/airflow.go
  ext/scheduler/airflow2/airflow_test.go
  job/deployer.go
  job/deployer_test.go
  job/service.go
  job/service_test.go
  mock/scheduler.go
  models/scheduler.go
Labels: bug

#607 refactor: unify job spec repository
  api/handler/v1beta1/adapter_test.go
  api/handler/v1beta1/job_run_test.go
  api/handler/v1beta1/job_spec_test.go
  client/local/job_spec_adapter_test.go
  client/local/job_spec_repository_test.go
  compiler/job_asset_compiler_test.go
  compiler/job_run_input_compiler_test.go
  datastore/backup_test.go
  go.mod
  go.sum
  internal/store/postgres/adapter.go
  internal/store/postgres/hook_run_repository_test.go
  internal/store/postgres/instance_repository_test.go
  internal/store/postgres/job_run_repository_test.go
  internal/store/postgres/job_source_repository.go
  internal/store/postgres/job_source_repository_test.go
  internal/store/postgres/job_spec_repository.go
  internal/store/postgres/job_spec_repository_test.go
  internal/store/postgres/jobrun_old_repository_test.go
  internal/store/postgres/namespace_job_spec_repository.go
  internal/store/postgres/namespace_job_spec_repository_test.go
  internal/store/postgres/project_job_spec_repository.go
  internal/store/postgres/project_job_spec_repository_test.go
  internal/store/postgres/record_test.go
  internal/store/postgres/replay_repository_test.go
  internal/store/postgres/sensor_run_repository_test.go
  internal/store/postgres/task_run_repository_test.go
  internal/store/store.go
  job/dependency_resolver.go
  job/dependency_resolver_test.go
  job/deployer.go
  job/deployer_test.go
  job/replay_test.go
  job/service.go
  job/service_test.go
  mock/job.go
  mock/plugin.go
  server/dependencies.go
  server/optimus.go
  service/job_run_service_test.go
  service/plugin_service_test.go
  tests/bench/1_job_spec_repo_test.go
  tests/bench/replay_repo_test.go
  tests/setup/plugin.go
Labels: refactor

#625 test: add tag on unit test to fix coverage report
  internal/store/postgres/record_test.go
Labels: test
