Repository odpf/optimus, pull requests merged in 2022-01, with the labels that each got.

#80 Cleanup
  Makefile
Labels: refactor

#130 feat: progress bar during specification deployment in cli
  README.md
  cmd/admin.go
  cmd/admin_build_instance.go
  cmd/backup.go
  cmd/backup_create.go
  cmd/backup_list.go
  cmd/backup_status.go
  cmd/commands.go
  cmd/config.go
  cmd/deploy.go
  cmd/job.go
  cmd/job_create.go
  cmd/job_hook.go
  cmd/job_render.go
  cmd/job_run.go
  cmd/job_status.go
  cmd/job_validate.go
  cmd/progressbar.go
  cmd/replay.go
  cmd/replay_create.go
  cmd/replay_list.go
  cmd/replay_status.go
  cmd/resource.go
  cmd/serve.go
  cmd/version.go
  config/loader.go
  config/telemetry.go
  docs/docs/getting-started/configuration.md
  docs/docs/guides/adding-hook.md
  docs/docs/guides/backup.md
  docs/docs/guides/create-bigquery-dataset.md
  docs/docs/guides/create-bigquery-external-table.md
  docs/docs/guides/create-bigquery-table.md
  docs/docs/guides/create-bigquery-view.md
  docs/docs/guides/create-job.md
  docs/docs/guides/predator.md
  docs/docs/guides/publishing-from-bigquery-to-kafka.md
  docs/docs/guides/replay.md
  docs/docs/guides/task-bq2bq.md
  go.mod
  go.sum
  main.go
  scripts/smoke-test.sh
Labels: enhancement, refactor

#133 fix: rerunning an old job cause task and hook execution time to differ
  cmd/deploy.go
  cmd/job_validate.go
  config/loader.go
  mock/github.go
  mock/http.go
  mock/instance.go
  models/instance.go
  models/job.go
  run/service.go
  run/service_test.go
  store/postgres/job_spec_adapter.go
Labels: bug

#135 fix: empty metadata during job creation panics the server
  api/handler/v1beta1/adapter.go
  ext/datastore/bigquery/adapter.go
Labels: bug
